
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        # Build the Docker image
        docker build -t sayyamdev/test-project:latest .

    - name: Push Docker image to Docker Hub
      run: |
        # Push the image to Docker Hub
        docker push sayyamdev/test-project:latest

    - name: Set up SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key.pem
        chmod 600 /tmp/private_key.pem
        
    - name: SSH into VM, Pull latest code, and copy to container
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem ubuntu@${{ secrets.VM_IP }} << 'EOF'
          # Go to the project directory
          # Deployment
          kubectl apply -f deployment.yml
          
          # Trigger a rollout to apply the changes
          kubectl rollout restart deployment/hello-world-app
        EOF
      env:
        VM_IP: ${{ secrets.VM_IP }}
