name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save SSH Key to a File
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key.pem
      shell: bash

    - name: Set Permissions for the Private Key
      run: chmod 600 /tmp/private_key.pem
      shell: bash

    - name: SSH into VM, Pull Latest Code, Build Docker Image, and Deploy to Kubernetes
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem ubuntu@3.144.232.45 \
        "cd /home/ubuntu/app && \
         git pull origin main && \
         docker build -t hello-world-app:latest . && \
         kubectl set image deployment/hello-world-app hello-world=hello-world-app:latest && \
         kubectl rollout status deployment/hello-world-app"
      shell: bash

