name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Save SSH Key to a File
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key.pem
      shell: bash

    - name: Set Permissions for the Private Key
      run: chmod 600 /tmp/private_key.pem
      shell: bash

    - name: SSH into VM, Pull Latest Code, Build Docker Image, and Deploy to Kubernetes
      run: |
        ssh -i /tmp/private_key.pem ubuntu@3.144.232.45 << 'EOF'
          # Go to the project directory
          cd /home/ubuntu/app

          # Pull the latest code from the repository
          git pull origin main

          # Build the Docker image locally on the VM
          docker build -t hello-world-app:latest .

          # Deploy the image to Kubernetes
          kubectl set image deployment/hello-world-app hello-world=hello-world-app:latest

          # Wait for the Kubernetes deployment to be updated
          kubectl rollout status deployment/hello-world-app
        EOF
      shell: bash
